name: Release

# Only trigger, when the test workflow succeeded
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.owner }}
          repo: ${{ github.repo }}
          name: ${{ github.ref }}
          body: ${{ github.head_commit.message }}
          draft: false
          prerelease: false
