name: Release

# Only trigger, when the test workflow succeeded
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - run: npm ci
      - run: npm run release

      - name: Release
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
